set(QML_FILES
    qml/Main.qml
    qml/themes/Theme.qml
    qml/controls/VTabButton.qml
    qml/layouts/VTabBar.qml
    qml/controls/VLayerButton.qml
    qml/layouts/layers/VLayerContainer.qml
    qml/controls/VLayerControl.qml
    qml/views/Layers.qml
    qml/layouts/layers/VLayersControlContainer.qml
    qml/controls/VGroupBox.qml
    qml/controls/VKnob.qml
    qml/controls/VSplitView.qml
    qml/views/Settings.qml
    qml/layouts/settings/TabBarSettings.qml
    qml/controls/VSlider.qml
    qml/layouts/settings/settingsPages/ConnectionsPage.qml
    qml/controls/VComboBox.qml
    qml/controls/VButton.qml
    qml/controls/VPopup.qml
    qml/controls/VSliderPopup.qml
    qml/controls/VSliderPopupH.qml
)
